os: linux
language: python

addons:
  apt:
    packages:
      - clang-format

notifications:
  slack:
    secure: "gNmDj2oHwuqoOwHKFZqooYiiIwKVWLtR4JSEDVNqYakmR8RGevYC8xTQD3cY6GtOJJKEYKKpvpsgCgYTGlO2XLZoJeivBI+P5C61k7ADi0OQUOHfofwlkcMXuKboEmcg7HevsgaKT8OP9aaSTjjyhwUVmTM1Nnqo1jNmjyitaM6aqFDarUJtKu02sCA9i9a0bJ2p9+hGVAPUJV6WcfwqEw+SQP2nLfb5b14F7Ruq0DGw7h5WT6Bjxz8iyppI7PTeVqaGYkGpNsn3lBk6dTUU91gYmtEBL5vJP6mzSwATztCRSWZ8WQjWljKe2r7y5sRcWm6RylAQutFLsLBvF5HuXto9g8pW+j8N8I0ZkQe1TWxsNk7xYyqa3k5dDs94GPIfCuaV2swR8AjwyHe9Wc3ljr0GGwDVssFeRv6cHAu2N03ASKo8Ih+Vg0MT0S9LZ8uDw8ulxmlws/PjBnO8WylKNJhOG3fFroVCGyIv2iHlgJNAoIjo5M4+eTF7qCAMFGrEkh2kKWyIBbExDvFckwlJYmnpnRpf1+0YpGJKRinxWRoEmDpo6PeMiYlkKBVmmhQ48dmRBwVj6C6le7w9fn4coN8TFgZkIgPRJ7TS94hIyNOKITetmibqsPX92a0T+PZzkwgZ1Pfun4M+asfznZNWZ/eIJ77MoTEmYyD6b+UuiS0="
  email: false

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update
  - platformio lib install

script:
  - platformio run
  - platformio test --environment native
  - platformio check --fail-on-defect high
  - wget -qO- https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py | python - -r src include test
